/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     07/06/2024 16:45:27                          */
/*==============================================================*/


ALTER TABLE ACTIVIDAD
    DROP FOREIGN KEY IF EXISTS FK_ACTIVIDA_PERTENECE_PROGRAMA;

ALTER TABLE EMPLEA
    DROP FOREIGN KEY IF EXISTS FK_EMPLEA_EMPLEA2_ACTIVIDA,
    DROP FOREIGN KEY IF EXISTS FK_EMPLEA_EMPLEA_MATERIAL;

ALTER TABLE ESTADO_SALUD
    DROP FOREIGN KEY IF EXISTS FK_ESTADO_S_POSEE_NINIO;

ALTER TABLE MATRICULA
    DROP FOREIGN KEY IF EXISTS FK_MATRICUL_RELATIONS_ANO_LECT,
    DROP FOREIGN KEY IF EXISTS FK_MATRICUL_RELATIONS_NINIO;

ALTER TABLE NINIO
    DROP FOREIGN KEY IF EXISTS FK_NINIO_POSEE_UN__GENERO,
    DROP FOREIGN KEY IF EXISTS FK_NINIO_PRESENTAN_TALLA_ZA,
    DROP FOREIGN KEY IF EXISTS FK_NINIO_PRESENTA__TALLA_VE,
    DROP FOREIGN KEY IF EXISTS FK_NINIO_TIENEN_NA_NACIONAL;

ALTER TABLE PADRE
    DROP FOREIGN KEY IF EXISTS FK_PADRE_POSEE_UNA_NACIONAL,
    DROP FOREIGN KEY IF EXISTS FK_PADRE_POSEE_UN__GENERO;

ALTER TABLE PROFESIONAL
    DROP FOREIGN KEY IF EXISTS FK_PROFESIO_POSEE_UN__GENERO,
    DROP FOREIGN KEY IF EXISTS FK_PROFESIO_PROPONE_ACTIVIDA,
    DROP FOREIGN KEY IF EXISTS FK_PROFESIO_TIENE_MAC_NACIONAL;

ALTER TABLE PROGRAMA
    DROP FOREIGN KEY IF EXISTS FK_PROGRAMA_RELATIONS_ANO_LECT;

ALTER TABLE RELACION_PADRE_NINIO
    DROP FOREIGN KEY IF EXISTS FK_RELATION_RELATIONS_NINIO,
    DROP FOREIGN KEY IF EXISTS FK_RELATION_RELATIONS_PADRE;

ALTER TABLE RENDIMIENTO
    DROP FOREIGN KEY IF EXISTS FK_RENDIMIE_RELATIONS_ACTIVIDA,
    DROP FOREIGN KEY IF EXISTS FK_RENDIMIE_RELATIONS_NINIO,
    DROP FOREIGN KEY IF EXISTS FK_RENDIMIE_RELATIONS_TIPO_REN;

ALTER TABLE SALUD_ALERGIAS_RELATION
    DROP FOREIGN KEY IF EXISTS FK_SALUD_AL_SALUD_ALE_ALERGIAS,
    DROP FOREIGN KEY IF EXISTS FK_SALUD_AL_SALUD_ALE_ESTADO_S;

ALTER TABLE SALUD_MEDICAMENT_RELATION
    DROP FOREIGN KEY IF EXISTS FK_SALUD_ME_SALUD_MED_ESTADO_S,
    DROP FOREIGN KEY IF EXISTS FK_SALUD_ME_SALUD_MED_MEDICAME;

ALTER TABLE TUTOR
    DROP FOREIGN KEY IF EXISTS FK_TUTOR_MANTIENE__RELACION,
    DROP FOREIGN KEY IF EXISTS FK_TUTOR_POSEE_UN__GENERO,
    DROP FOREIGN KEY IF EXISTS FK_TUTOR_TIENEN_NA_NACIONAL;

ALTER TABLE TUTORES_NINIOS_RELATION
    DROP FOREIGN KEY IF EXISTS FK_TUTORES__TUTORES_N_NINIO,
    DROP FOREIGN KEY IF EXISTS FK_TUTORES__TUTORES_N_TUTOR;

DROP TABLE IF EXISTS ACTIVIDAD,
                    ALERGIAS,
                    ANO_LECTIVO,
                    EMPLEA,
                    ESTADO_SALUD,
                    GENERO,
                    MATERIAL,
                    MATRICULA,
                    MEDICAMENTO,
                    NACIONALIDAD,
                    NINIO,
                    PADRE,
                    PROFESIONAL,
                    PROGRAMA,
                    RELACION,
                    RELACION_PADRE_NINIO,
                    RENDIMIENTO,
                    SALUD_ALERGIAS_RELATION,
                    SALUD_MEDICAMENT_RELATION,
                    TALLA_VESTIMENTA,
                    TALLA_ZAPATO,
                    TIPO_RENDIMIENTO,
                    TUTOR,
                    TUTORES_NINIOS_RELATION;